/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  albertotuzzi
 * Created: Jul 11, 2016
 */

CREATE TABLE CLIENTE (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome VARCHAR(128),
 cognome VARCHAR(128),
 username VARCHAR(128),
 password VARCHAR(128),
 credito FLOAT       );

CREATE TABLE VENDITORE (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome VARCHAR(128),
 cognome VARCHAR(128),
 username VARCHAR(128),
 password VARCHAR(128),
 credito FLOAT       );

CREATE TABLE ARTICOLO (
 code INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome VARCHAR(128),
 descrizione VARCHAR(128),
 quant INTEGER,
 url VARCHAR(128),
 prezzo FLOAT,
 vend INTEGER,
FOREIGN KEY (vend) REFERENCES venditore(id)
                     );
